homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 105
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

wink:

wemo:
  static:
    - 192.168.1.207

ifttt:
  key: !secret ifttt_key

neato:
  username: !secret neato_username
  password: !secret neato_password

google:
  client_id: !secret google_apis_client_id
  client_secret: !secret google_apis_client_secret

group: !include groups.yaml
script: !include scripts.yaml
automation: !include automations.yaml
weblink: !include weblinks.yaml
sensor: !include sensors.yaml
camera: !include cameras.yaml
notify: !include notifications.yaml
media_player: !include media_players.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
device_tracker: !include device_trackers.yaml
