homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  # Customization file
  customize: !include include/customize.yaml

# Enables the map
map:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Enable iOS Hub
ios:

abode: !include include/abode.yaml
automation: !include include/automations.yaml
binary_sensor: !include include/binary_sensors.yaml
camera: !include include/cameras.yaml
climate: !include include/climate.yaml
device_tracker: !include include/device_trackers.yaml
frontend: !include include/frontend.yaml
google: !include include/google.yaml
group: !include include/groups.yaml
http: !include include/http.yaml
ifttt: !include include/ifttt.yaml
input_boolean: !include include/input_booleans.yaml
input_number: !include include/input_numbers.yaml
light: !include include/lights.yaml
media_player: !include include/media_players.yaml
neato: !include include/neato.yaml
nest: !include include/nest.yaml
notify: !include include/notifications.yaml
script: !include include/scripts.yaml
sensor: !include include/sensors.yaml
tts: !include include/tts.yaml
weather: !include include/weather.yaml
weblink: !include include/weblinks.yaml
wemo: !include include/wemo.yaml
zone: !include include/zones.yaml
