resources:
  - url: /local/cards/ciotlosm/custom-lovelace/alarm_control_panel-card/alarm_control_panel-card.js?v=0.3.1
    type: js

views:
  - icon: mdi:home
    title: Home
    id: home
    cards:
      - type: vertical-stack
        cards:
          - type: entity-filter
            entities:
              - sensor.pws_alerts
            state_filter:
              - '1'
              - '2'
              - '3'
              - '4'
            card:
              type: markdown
              content: >
                ## {{ sensor.pws_alerts.attributes.Description }}

                {{ sensor.pws_alerts.attributes.Message }}

                Expires at {{ sensor.pws_alerts.attributes.Expires }}
            show_empty: false

          - type: weather-forecast
            entity: weather.yweather

          - type: picture-entity
            entity: camera.weather_radar
            show_info: false

      - type: custom:alarm_control_panel-card
        title: Abode Home Security
        entity: alarm_control_panel.abode_home_security
        hide_keypad: false
        states:
          - arm_home
          - arm_away

      - type: markdown
        title: Local Phone Numbers
        content: >
          **Sheriff's Office**: [(804) 598-5656](tel:8045985656)

          **Fire & Rescue**: [(804) 598-5646](tel:8045985646)

          **Animal Control**: [(804) 598-5672](tel:8045985672)

      - type: entities
        title: Alarm Clocks
        entities:
          - input_boolean.weekday_alarm_clock_status
          - sensor.weekday_alarm_clock_time
          - input_number.weekday_alarm_clock_hour
          - input_number.weekday_alarm_clock_minute
          - input_boolean.weekend_alarm_clock_status
          - sensor.weekend_alarm_clock_time
          - input_number.weekend_alarm_clock_hour
          - input_number.weekend_alarm_clock_minute
          - input_boolean.onetime_alarm_clock_status
          - sensor.onetime_alarm_clock_time
          - input_number.onetime_alarm_clock_hour
          - input_number.onetime_alarm_clock_minute
        show_header_toggle: false

      - type: entities
        title: Heating & Cooling
        entities:
          - climate.downstairs
          - climate.upstairs

      - type: entities
        title: Water Heater(s)
        entities:
          - climate.primary_water_heater

      - type: glance
        title: Calendar Events
        entities:
          - calendar.contacts
          - calendar.day_off
          - calendar.holidays_in_united_states
          - calendar.personal
          - calendar.vacation
          - calendar.work

  - icon: mdi:sofa
    title: Downstairs
    id: downstairs
    cards:
      - type: entities
        title: Heating & Cooling
        entities:
          - climate.downstairs

#      - type: picture-glance
      - type: picture-entity
        title: Kitchen
        entity: camera.kitchen
#        camera_image: camera.kitchen
#        entities:
#          - light.

#      - type: picture-glance
      - type: picture-entity
        title: Dining
        entity: camera.dining
#        camera_image: camera.dining
#        entities:
#          - light.

#      - type: picture-glance
      - type: picture-entity
        title: Foyer
        entity: camera.foyer
#        camera_image: camera.foyer
#        entities:
#          - light.

#      - type: picture-glance
#        title: Utility
#        camera_image: camera.utility
#        entities:
#          - light.

#      - type: picture-glance
#        title: Garage
#        camera_image: camera.garage
#        entities:
#          - light.

      - type: picture-glance
        title: Living Room
        camera_image: camera.living_room
        entities:
          - light.living_room_lamp

      - type: picture-glance
        title: Neato
        camera_image: camera.neato_downstairs_cleaning_map
        entities:
          - vacuum.neato_downstairs

  - icon: mdi:hotel
    title: Upstairs
    id: upstairs
    cards:
      - type: entities
        title: Heating & Cooling
        entities:
          - climate.upstairs

#      - type: picture-glance
      - type: picture-entity
        title: Master Bedroom
        entity: camera.master_bedroom
#        camera_image: camera.master_bedroom
#        entities:
#          - light.

#      - type: picture-glance
      - type: picture-entity
        title: Master Bathroom
        entity: camera.master_bathroom
#        camera_image: camera.master_bathroom
#        entities:
#          - light.

#      - type: picture-glance
      - type: picture-entity
        title: Guest Bathroom
        entity: camera.guest_bathroom
#        camera_image: camera.guest_bathroom
#        entities:
#          - light.

#      - type: picture-glance
      - type: picture-entity
        title: Guest Bedroom
        entity: camera.guest_bedroom1
#        camera_image: camera.guest_bedroom1
#        entities:
#          - light.

#      - type: picture-glance
#        title: Guest Bedroom
#        camera_image: camera.guest_bedroom2
#        entities:
#          - light.

      - type: picture-glance
        title: Office
        camera_image: camera.office
        entities:
          - light.office_lights

      - type: picture-glance
        title: Neato
        camera_image: camera.neato_upstairs_cleaning_map
        entities:
          - vacuum.neato_upstairs

  - icon: mdi:garage
    title: Garage
    id: garage
    cards:
      - type: media-control
        entity: media_player.garage_tv

  - icon: mdi:pine-tree
    title: Outdoors
    id: outdoors
    cards:
      - type: picture-glance
        title: Front Porch
        camera_image: camera.front_porch
        entities:
          - light.porch_lights

      - type: picture-glance
        title: Walkway
        camera_image: camera.walkway
        entities:
          - switch.wemo_walkway_lights

      - type: picture-glance
        title: Driveway
        camera_image: camera.driveway
        entities:
          - light.driveway_lights

      - type: weather-forecast
        entity: weather.yweather

      - type: picture-entity
        entity: camera.weather_radar
        show_info: false

  - icon: mdi:shield
    title: Security
    id: security
    cards:
      - type: custom:alarm_control_panel-card
        title: Abode Home Security
        entity: alarm_control_panel.abode_home_security
        hide_keypad: false
        states:
          - arm_home
          - arm_away

      - type: entity-filter
        entities:
          - sensor.abode_sensor_dining_room_window_left
          - sensor.abode_sensor_dining_room_window_right
          - sensor.abode_sensor_front_door
          - sensor.abode_sensor_garage_door
          - sensor.abode_sensor_garage_entry_door
          - sensor.abode_sensor_garage_window_left
          - sensor.abode_sensor_garage_window_right
          - sensor.abode_sensor_guest_bedroom_window
          - sensor.abode_sensor_home_gym_window
          - sensor.abode_sensor_home_office_window_left
          - sensor.abode_sensor_home_office_window_right
          - sensor.abode_sensor_keypad_foyer
          - sensor.abode_sensor_keypad_garage
          - sensor.abode_sensor_kitchen_window
          - sensor.abode_sensor_living_room_glass_break
          - sensor.abode_sensor_living_room_window_left
          - sensor.abode_sensor_living_room_window_right
          - sensor.abode_sensor_master_backyard_window
          - sensor.abode_sensor_master_bath_window_left
          - sensor.abode_sensor_master_bath_window_right
          - sensor.abode_sensor_master_driveway_window_left
          - sensor.abode_sensor_master_driveway_window_right
          - sensor.abode_sensor_patio_door
          - sensor.abode_sensor_patio_window_left
          - sensor.abode_sensor_patio_window_right
          - sensor.abode_sensor_siren_downstairs
          - sensor.abode_sensor_stairs_window
        state_filter:
          - 'Low Battery'
          - 'Open'
          - 'Offline'
        card:
          type: glance
          title: Security Vulnerabilities
        show_empty: false

      - type: glance
        title: Entry Doors
        entities:
          - sensor.abode_sensor_front_door
          - sensor.abode_sensor_garage_door
          - sensor.abode_sensor_garage_entry_door
          - sensor.abode_sensor_patio_door

      - type: glance
        title: Windows (Downstairs)
        entities:
          - sensor.abode_sensor_dining_room_window_left
          - sensor.abode_sensor_dining_room_window_right
          - sensor.abode_sensor_garage_window_left
          - sensor.abode_sensor_garage_window_right
          - sensor.abode_sensor_kitchen_window
          - sensor.abode_sensor_living_room_window_left
          - sensor.abode_sensor_living_room_window_right
          - sensor.abode_sensor_patio_window_left
          - sensor.abode_sensor_patio_window_right
          - sensor.abode_sensor_stairs_window

      - type: glance
        title: Windows (Upstairs)
        entities:
          - sensor.abode_sensor_guest_bedroom_window
          - sensor.abode_sensor_home_gym_window
          - sensor.abode_sensor_master_backyard_window
          - sensor.abode_sensor_master_driveway_window_left
          - sensor.abode_sensor_master_driveway_window_right
          - sensor.abode_sensor_master_bath_window_left
          - sensor.abode_sensor_master_bath_window_right
          - sensor.abode_sensor_home_office_window_left
          - sensor.abode_sensor_home_office_window_right

  - icon: mdi:account-key
    title: Administration
    id: administration
    cards:
      - type: entities
        title: Automations
        entities:
          - group.all_automations

      - type: entities
        title: Scripts
        entities: 
          - group.all_scripts

      - type: entities
        title: Links
        entities:
          - weblink.pfsense
          - weblink.wireless_ap_home
          - weblink.wireless_ap_garage
          - weblink.plex
          - weblink.obi200
          - weblink.resilio_sync

      - type: entities
        title: Calendars
        entities:
          - group.calendar
